# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: danielqsj/kafka-exporter
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: "kafka-exporter"
fullnameOverride: "kafka-exporter"

# the host:port of one of the kafka servers in your cluster
kafka:
  server: ""

service:
  namespace: default
  type: ClusterIP
  port: 9308

serviceMonitor:
  enabled: true
  namespace: monitoring
  annotations: {}
  # Add whatever label the Prometheus service is looking for so this
  # ServiceMonitor will be automatically picked up.
  labels: 
    release: mon
  interval: 30s
  path: /metrics

resources: {}
